metacritic_mapping = {
    # These first several films lack metacritic reviews,
    # and are unlikely to ever get them.
    # "The Ascent": ,
    # "Troll 2": ,
    # "Memories": ,
    # "Air Bud": ,
    # "Rampant": ,
    # "Inspector Ike": ,
    # "Nate - A One Man Show": ,
    "Pokemon 2000": 0.28,
    "Hundreds of Beavers": 0.82,
    "The Holdovers": 0.82,
    "The Wonderful Story of Henry Sugar": 0.85,
    "El Conde": 0.72,
    "American Fiction": 0.81,
    "Sing Sing": 0.85,
    "Outlaw Johnny Black": 0.54,
    "Saltburn": 0.61,
    "Silent Night": 0.53,
    "The Boy and the Heron": 0.91,
    "Society of the Snow": 0.72,
    "Migration": 0.56,
    "All of Us Strangers": 0.9,
    "The Teachers' Lounge": 0.82,
    "Godzilla Minus One": 0.81,
    "Upgraded": 0.59,
    "Molli and Max in the Future": 0.7,
    "Drive-Away Dolls": 0.56,
    "Love Lies Bleeding": 0.77,
    "The Beast": 0.8,
    "Civil War": 0.75,
    "Challengers": 0.82,
    "Evil Does Not Exist": 0.83,
    "Slow": 0.72,
    "Gasoline Rainbow": 0.8,
    "Babes": 0.71,
    "Furiosa: A Mad Max Saga": 0.79,
    "I Used to Be Funny": 0.74,
    "Ghostlight": 0.83,
    "Thelma": 0.77,
    "Oddity": 0.78,
    # This next film currently has too few reviews, bc it
    # only just came out (written 8/7/24).
    # "The Nature of Love": ,
}


rt_mapping = {
    # The following commented out film lacks an RT score.
    # "Memories": ,
    "Pokemon 2000": 0.19,
    "Possessor": 0.94,
    "The Card Counter": 0.87,
    "TÃ¡r": 0.91,
    "Suzume": 0.96,
    "Talk to Me": 0.94,
}
