metacritic_mapping = {
    # "Salo": ,
	# "The Ascent": ,
	# "Troll 2": ,
	# "Memories": ,
	# "Air Bud": ,
	# "Rampant": ,
	# "Nate - A One Man Show": ,
	# "Inspector Ike": ,
	# "Sirocco and the Kingdom of the Winds": ,
	"Pokemon 2000": 0.28,
	"Hundreds of Beavers": 0.82,
	"The Holdovers": 0.82,
    "The Wonderful Story of Henry Sugar": 0.85,
    "El Conde": 0.72,
    "American Fiction": 0.81,
	"Quiz Lady": 0.59,
	"Sing Sing": 0.84,
	"Outlaw Johnny Black": 0.54,
    "Janet Planet": 0.83,
    "Wingwomen": 0.54,
    "Saltburn": 0.61,
	"Silent Night": 0.53,
	"The Boy and the Heron": 0.91,
	"All of Us Strangers": 0.9,
	"Society of the Snow": 0.72,
	"Migration": 0.56,
	"The Teachers' Lounge": 0.82,
	"Good One": 0.87,
	"Godzilla Minus One": 0.81,
	"Upgraded": 0.59,
	"Molli and Max in the Future": 0.7,
	"Drive-Away Dolls": 0.56,
	"Love Lies Bleeding": 0.77,
	"Do Not Expect Too Much from the End of the World": 0.95,
    "The Beast": 0.8,
    "Civil War": 0.75,
    "Challengers": 0.82,
	"Slow": 0.72,
	"Evil Does Not Exist": 0.83,
	"Gasoline Rainbow": 0.8,
    "Babes": 0.71,
    "Furiosa: A Mad Max Saga": 0.79,
    "I Used to Be Funny": 0.74,
    "Ghostlight": 0.83,
    "Thelma": 0.77,
	"The Nature of Love": 0.8,
	"Oddity": 0.78,
	"Only the River Flows": 0.7,
	"His Three Daughters": 0.84,
}


rt_mapping = {
    # The following commented-out film indeed lacks a Rotten Tomatoes review.
    # "Memories": ,
    # "Sirocco and the Kingdom of the Winds": ,
    "Pokemon 2000": 0.19,
    "Possessor": 0.94,
    "The Card Counter": 0.87,
    "TÃ¡r": 0.91,
    "Suzume": 0.96,
    "Talk to Me": 0.94,
}


imdb_mapping = {
	"Sirocco and the Kingdom of the Winds": 0.71,
	"His Three Daughters": 0.76,
}